### ISSUE TITLE
How to use your deploy tool  on go project?

### ISSUE THREAD

**Issue by wyh770406** [toggl/crap#7]
Could you give an example or show the Usage on ReadMe like other repos on github?
you just fired one line A deployment tool similar to Capistrano, but simplerer.

How to use in specific?

**Comment by IndrekV** [comment]
Thank you for your interest. I will add instructions to the Readme.

**Comment by IndrekV** [comment]
In short `crap crapify` generates sample configuration file. Editing that and executing crap should get you working.
